### ISSUE TITLE
Test against many DSPy use cases and different models from unify

### ISSUE THREAD

**Issue by OscarArroyoVega** [OscarArroyoVega/dspy#11]
install requirements:

`git+https://github.com/OscarArroyoVega/dspy.git@add_unify_client                              
unifyai`

try a dspy minimum working example with unify client

**Comment by Sanjay8602** [comment]
I am testing it with many unify.clients

**Comment by OscarArroyoVega** [comment]
Hello @Sanjay8602, Would you like to make some documentation improvements so you will appear as a contributor in this integration (because this test will not).  As reference, pick the Unify documentation style: https://github.com/unifyai/unify/blob/main/unify/clients.py and the branch/ file you can document is this: https://github.com/OscarArroyoVega/dspy/blob/add_unify_client/dsp/modules/unify.py

**Comment by Sanjay8602** [comment]
ok sure. And now this my work please do not give this work to other
